#!/bin/bash

echo " "
echo "***** Add users *****"
echo " "

for user in $(cat /opt/scripts/users); do
    set -e
    echo "[TASK $((++count))] Adding ${user} user"
    useradd ${user}
    echo "user ${user} added!"
    echo " "
done
